keep-starknet-strange/unruggable.meme

frontend/craco.config.cjs
frontend/package.json
frontend/src/components/Button/index.tsx
frontend/src/components/Button/style.css.ts
frontend/src/components/Input/index.tsx
frontend/src/components/WalletModal/Option.tsx
frontend/src/components/WalletModal/Overview.tsx
frontend/src/components/Web3Provider/index.tsx
frontend/src/pages/Launch/index.tsx
frontend/src/pages/Launch/style.css.ts
frontend/src/theme/components/Text.tsx
frontend/src/theme/css/sprinkles.css.ts
frontend/src/theme/css/vars.css.ts
frontend/yarn.lock

I setup the launch token form. The deploy button doesn't do anything because 1) token not deployed? 2) I need to update starknet react so it plays nicely with react-hook-form.
https://github.com/keep-starknet-strange/unruggable-memecoin/assets/282580/54516f5c-fb67-422d-a798-77d3ec7113cf

Setup launch token form

---

contracts/.tool-versions
contracts/Scarb.toml
contracts/src/lib.cairo
contracts/src/tokens/interface.cairo
contracts/src/tokens/memecoin.cairo
contracts/tests/test_unruggable_memecoin.cairo

- Refactors to use ERC20 components
- Entrypoints imported from components are only ERC20Metadata as, I think we're going to modify the other ones
- We, however, use internals from ERC20Internal in our custom entrypoints
- The `_transfer` function is redfined in an `Internal` impl, because we will very likely use a custom one
- Integration of all the entrypoints, embedded or not, is tested.

refactor: use ERC20 component

---

frontend/src/components/Layout/App/index.tsx
frontend/src/components/NavBar/Mobile/index.tsx
frontend/src/components/NavBar/Mobile/style.css.ts
frontend/src/components/NavBar/index.tsx
frontend/src/components/NavBar/style.css.ts

add a responsive NavBar at the bottom of the screen on mobile.
fix (#12)

responsive NavBar

---

frontend/src/App.tsx
frontend/src/components/NavBar/index.tsx
frontend/src/pages/Screen/index.tsx
frontend/src/pages/Screen/style.css.ts

front au the screener page
include spec from issue #21

feat: screener front

---

frontend/src/components/NumberInput/index.tsx
frontend/src/components/NumberInput/style.css.ts
frontend/src/pages/Launch/index.tsx

- Added a `NumberInput` component with formatting,
- Removed the default value of `10,000,000,000` of the inital supply & set as a placeholder.
@0xChqrles Let me know if I should it differently!

[frontend] feat: number input

---

contracts/src/tokens/interface.cairo
contracts/src/tokens/memecoin.cairo
contracts/tests/test_unruggable_memecoin.cairo

implement check maximum buy percentage #6
```js
fn check_max_buy_percentage(self: @ContractState, amount: u256)
```
Test function
```js
test_transfer_max_percentage()
test_transfer_from_max_percentage()
```
We need the launch phase logic to check the max percentage only during the launch duration
Suggestion: 
Add a set_max_percentage function for custom setting

feat: add maximum buy percentage

---

contracts/src/tokens/memecoin.cairo
contracts/tests/test_unruggable_memecoin.cairo

Resolves #77.
Also brings some modifications to the `_enforce_holders_limit` internal.  The method can also decrease holders count if the sender has no tokens left after the transfer.
Lastly, it might be interesting to discuss about adding additional checks in the `_enforce_holders_limit` such as asserting the `amount` param or `recipient` are not null. With current ERC20 implementation, those checks are useless, but it makes this method rely on ERC20 behaviour. Without those checks, this method is a kind of ERC20 extension, which is not a bad design, but also not necessarily what we want.

redesign initial distribution logic

---

contracts/src/tokens/factory.cairo
contracts/tests/test_unruggable_memecoin.cairo
contracts/tests/test_unruggable_memecoin_factory.cairo

Providing contract address salt in factory calldata makes it easier for FE usage

add `contract_address_salt` in `create_memecoin` factory method

---

contracts/src/tokens/factory.cairo
contracts/src/tokens/memecoin.cairo
contracts/tests/test_token_locker.cairo
contracts/tests/test_unruggable_memecoin.cairo
contracts/tests/test_unruggable_memecoin_factory.cairo

move AMM mgmt from token to factory and keep the same calldata for `create_memecoin` and token constructor

move AMM mgmt from token to factory

---

contracts/src/tokens/interface.cairo
contracts/src/tokens/memecoin.cairo
contracts/tests/test_unruggable_memecoin.cairo

Please add the labels corresponding to the type of changes your PR introduces:
- Testing
- Bugfix
Current  `add_liquidity()`  function use `0` as deadline but this will always revert. Because for router contracts deadline should be bigger than current timestamp.
```
amm_router
.add_liquidity(
memecoin_address,
counterparty_token_address,
liquidity_memecoin_amount,
liquidity_counterparty_token,
1, // amount_a_min
1, // amount_b_min
memecoin_address,
0, // deadline
);
```
It is not good practise to use a constant as a deadline so I added a deadline as input.
```
fn launch_memecoin(
ref self: ContractState,
amm_v2: AMMV2,
counterparty_token_address: ContractAddress,
liquidity_memecoin_amount: u256,
liquidity_counterparty_token: u256,
deadline:u64
) -> ContractAddress {
```

fix deadline

---

contracts/src/tokens/factory.cairo
contracts/src/tokens/memecoin.cairo
contracts/tests/test_token_locker.cairo
contracts/tests/test_unruggable_memecoin.cairo

The test is not implemented. We need to have a function that successfully launches memecoin then we will be able to test that.
The test will be simple. Just increase the timestamp by 1000 after calling `launch_memecoin`
On the factory side, I passed `1000_u64` as the third param of the constructor of memecoin. It has to be changed by how you gonna use it from the factory.

Delay that bypasses transfer limit

---

contracts/src/tests.cairo
contracts/src/tests/test_memecoin_erc20.cairo
contracts/src/tests/test_unruggable_memecoin.cairo
contracts/src/tests/utils.cairo
contracts/src/tokens/memecoin.cairo

1. function `_check_and_update_tx_hash` added in order to check the tx_hash of the recipient in both transfer and transfer_from function.
2. previous test updated in order to give them a non-zero tx_hash (by default it 0x0)
3. new test added which panics when same tx_hash is having two different calls of same recipient.

test and feature added for multi call buy prevention

---

contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/lib.cairo
contracts/src/locker/token_locker.cairo
contracts/src/tests/test_factory.cairo
contracts/src/tests/test_token_locker.cairo
contracts/src/tests/test_unruggable_memecoin.cairo
contracts/src/tests/utils.cairo
contracts/src/tokens/interface.cairo
contracts/src/tokens/memecoin.cairo
contracts/src/utils/math.cairo

1. Cleans the implementation of memecoin:
- Removes legacy code
- Apply clean code good practices
- Correctly separate different concerns in different functions
- Remove deadline parameter to supply to the AMM router (its in the same block anyway 😵 )
2. Make `transfer_limit_delay` a parameter upon launch
3. Clear tests from useless tests (e.g testing that transferFrom fails when allowance is too low)

refactor: clean memecoin impl

---

contracts/src/amm/amm.cairo
contracts/src/tests/test_factory.cairo
contracts/src/tests/test_memecoin_erc20.cairo
contracts/src/tests/test_unruggable_memecoin.cairo
contracts/src/tests/utils.cairo
contracts/src/tokens/interface.cairo
contracts/src/tokens/memecoin.cairo

- use constant values for deployment test addresses
- use constant values for deployment variables
- clean deployment utils
- clean tests to use reusable deployment logic
- add ownership entrypoints to memecoin
- add entrypoints to get locker and factory addresses
This should be merged after #105 as it depends on it (and once 105 is merged, the base branch should be changed to main)

refactor: clean memecoin tests and impl

---

contracts/src/tests/test_unruggable_memecoin.cairo
contracts/src/tests/utils.cairo
contracts/src/tokens/memecoin.cairo

This PR disallows `ensure_not_multicall` if `transfer_delay` after launch has passed.
Closes #107

FEAT: disable multicall prevention after delay has passed

---

contracts/Scarb.toml
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/token/memecoin.cairo

feat: update multicall check to track `tx_origin`

---

contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/test_jediswap.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/test_memecoin_erc20.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/tests/unit_tests/utils.cairo
contracts/src/token/interface.cairo
contracts/src/token/memecoin.cairo

with this PR, transfer restriction delay has to be provided at memecoin launch instead of creation.

Setup Transfer restriction delay at launch

---

contracts/src/errors.cairo
contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/test_jediswap.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/utils.cairo
contracts/src/token/interface.cairo
contracts/src/token/memecoin.cairo

The max percentage buy limit was hardcoded to 2% before this PR, now it has to be provided during launch, and the value cannot fall behind 0.5%

Max percentage buy provided at launch

---

frontend/src/components/ImportTokenModal/index.tsx
frontend/src/components/ImportTokenModal/style.css.ts
frontend/src/pages/Home/index.tsx
frontend/src/pages/Launch/index.tsx

The "Check Token" button located on the homepage opens a modal, prompting the user to input a token address. If the entered address corresponds to an unruggable memecoin, the user will be redirected to the token's page. Otherwise, an error message will be displayed.

add check token on homepage

---

contracts/src/errors.cairo
contracts/src/token/memecoin.cairo

@credence0x  - [M-01]
The owner of the memecoin could be zero.
Mitigation:
Add a non-zero check

audit: prevent memecoin owner to be zero

---

contracts/src/token/memecoin.cairo

@credence0x - [U-01]
@0xEniotna - [O-01]
The zero address check is useless since the token can’t be minted to the zero address, can’t be burned and can’t be transferred to the zero address, the sender address would never be 0.
Mitigation:
Removed the check for `self.is_zero()`

audit: remove useless zero check

---

contracts/src/factory/factory.cairo

@credence0x - [U-03]
@0xEniotna - [O-04]
@ermvrs - [BP-05]
The `is_launched` check was duplicated
Mitigation:
Removed the second useless check.

audit: remove duplicated 'is_launched' check

---

contracts/src/factory/factory.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/tests/unit_tests/utils.cairo

@credence0x - [U-04]
@0xEniotna - [O-03]
@ermvrs - [I-02]
The factory uses the Ownable component and takes an owner upon deployment, which is not required.
Mitigation:
- Removed the ownable component
- Removed the owner constructor argument.

audit: remove factory owner

---

contracts/src/exchanges/ekubo/ekubo_adapter.cairo
contracts/src/exchanges/jediswap_adapter.cairo
contracts/src/factory/factory.cairo

@credence0x - [U-05]
@ermvrs - [BP-02] / [BP-06] / [BP-07]
- The variable `quote_balance` was not used
- The variables `quote_token` were not used
- The variable `caller_address` was not used
Mitigation:
Removed the variables.

audit: remove unused variables

---

contracts/src/errors.cairo
contracts/src/factory/factory.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/utils.cairo

@ermvrs - [L-01]
The factory could be used to launch tokens not created by the factory. If the token has the correct entrypoints, the call would not revert.
Mitigation:
Add a check to ensure the memecoin is an unruggable one.

audit: disable launch non-unruggable coins

---

contracts/src/locker/lock_manager.cairo

@ermvrs  - [BP-04]
@0xEniotna - [L-01]
The write is sequential to the read without any variable mutation, and thus is unnecessary.
Mitigation:
Removed the read and write.

audit: remove unnecessary write

---

contracts/src/tests/unit_tests.cairo
contracts/src/tests/unit_tests/test_utils.cairo
contracts/src/token/memecoin.cairo
contracts/src/utils.cairo

@ermvrs  - [I-01]
@credence0x - [H-02]
The number of initial holders can be gamed by supplying multiple times the same address
Mitigation:
Add a `unique` function that returns the count of unique occurences in an array.

audit: count unique holders at launch

---

contracts/src/exchanges/ekubo/launcher.cairo
contracts/src/token/memecoin.cairo

@ermvrs  - [BP-01]
These functions, intended to be used as view, were declared as external.
Mitigation:
Make them view

audit: make functions view instead of write

---

contracts/src/locker/lock_manager.cairo

@0xEniotna  - [L-02]
The CEI pattern was not respected
Mitigation:
Move interaction after effects.

audit: respect CEI pattern

---

contracts/src/tests/fork_tests/test_jediswap.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/token/memecoin.cairo

As reported by 
- @0xEniotna [C-01],
- @ermvrs [M-01]
The `get_caller_address() == pair` condition is true when the transaction is a BUY, hence the buy limits were never enforced.
Fix:
- return early only if `get_caller_address() != pair`, meaning that it's not a buy tx.

audit: fix buy restriction on jediswap

---

contracts/src/exchanges/ekubo/launcher.cairo
contracts/src/exchanges/jediswap_adapter.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/utils.cairo

@credence0x  - [C-01]
The problem was that if someone calls `create_pair` with the addresses of the memecoin and quote token, (not necessarily adding liquidity, just creating the pair), then the `launch_on_jediswap` call would fail as the pair already existed.
Also, the assertions on the balanceOf the pair could be gamed by a malicious actor that would send tokens to the pair so that it's un-launchable.
Mitigation:
- Remove `create_pair` call
- query `get_pair` to get the pair address
- Remove assertions on balanceOf pair.

audit: fix jediswap launch when the pair exists

---

contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/token/memecoin.cairo

@credence0x  - [H-01]
The problem was that if someone sends a token with `amount==0` pre-launch, the `prelaunch_holder_count` would be modified
Mitigation:
- Return early if the value is zero.

audit: fix prelaunch holder count change on zero value transfer

---

contracts/src/exchanges/ekubo/launcher.cairo
contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/mocks/jediswap/router.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/test_jediswap.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/test_jediswap_integration.cairo
contracts/src/token/memecoin.cairo
frontend/src/constants/misc.ts

As reported by 
- @ermvrs [L-02],
- @0xEniotna [L-04], 
- @credence0x [C-02]
The `ensure_not_multicall` would handicap aggregators as it would disable the possibility to transfer the token twice in the same transaction.
Mitigation:
Only add transfer checks when the transfer is in the context of a **BUY** transaction, namely
- When the caller is the jediswap pair itself OR when the caller is Ekubo Core itself.
This solution enables us to:
- Keep multicall prevention to disable multibuys in the same TX
- Make the coin compatible with aggregators (unless they buy on two different exchanges - but we assume that the liquidity will only be concentrated in a single pool, at least during the restriction phase)
As a counterparty, it
- Disables the transfer checks for other types of transactions. I …

audit: fix aggregator support

---

contracts/src/exchanges.cairo
contracts/src/exchanges/ekubo.cairo
contracts/src/exchanges/ekubo/ekubo_adapter.cairo
contracts/src/exchanges/ekubo/helpers.cairo
contracts/src/exchanges/ekubo/launcher.cairo
contracts/src/exchanges/jediswap_adapter.cairo
contracts/src/factory.cairo
contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/tests/addresses.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/test_jediswap.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/test_jediswap_integration.cairo
contracts/src/tests/unit_tests/test_lock_manager.cairo
contracts/src/tests/unit_tests/test_memecoin_erc20.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/tests/unit_tests/utils.cairo
contracts/src/token/interface.cairo
contracts/src/token/memecoin.cairo
contracts/src/utils.cairo

PR to prevent malicious interactions with ekubo by creating pools without any counterparty and risking the supply to dry up.
- Holders before launch is no longer a concept. The initial holders receive their tokens (for “free” ) once the coin is launched. As such, `pre_launch_holders_count` does not need to be tracked and enforcement of prelaunch holder count no longer makes sense.
- Allocation of team supply has moved from **memecoin.cairo** to **factory.cairo**
- All the initial tokens are minted to the factory
- The amount for the team allocation is written to the memecoin by the factory when finalising the launch.
- Factorized the assertions upon launch to avoid code duplication.
- Introduced the calculation of the supply held by the team, capped to 10%, by iterating through each …

refactor: distribute initial tokens only after launch and buy them from ekubo pool (if applicable)

---

contracts/src/exchanges/ekubo/ekubo_adapter.cairo
contracts/src/exchanges/jediswap_adapter.cairo
contracts/src/factory/factory.cairo
contracts/src/tests/fork_tests/test_ekubo.cairo
contracts/src/tests/fork_tests/utils.cairo
contracts/src/tests/unit_tests/test_factory.cairo
contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo
contracts/src/token/interface.cairo
contracts/src/token/memecoin.cairo

- Store liquidity parameters and block number at launch to allow FE to retrieve the mcap at launch without the need of an indexer. Useful feature to flag tokens launched with a very low mcap as potentially ruggable, or with an unknown quote token.
- Save lock position address at jediswap launch, to allow FE to retrieve the liquidity locking status without the need of an indexer.

[contracts] save liquidity parameters at launch

---

contracts/src/factory/factory.cairo
contracts/src/factory/interface.cairo
contracts/src/tests/unit_tests/test_factory.cairo

In factory constructor, implement a way to also migrate memecoin's locker manager

[contracts] migrate locker manager on factory constructor

---

frontend/src/App.tsx
frontend/src/pages/SignTransaction/SignTransaction.tsx
frontend/src/pages/SignTransaction/style.css.ts

This page is intended to be used with the Telegram bot. If the user is in desktop, user can choose the option to sign the transaction with the desktop web browser. User then redirected to this page to sign the transaction and deploy or launch the token.
Related
- https://github.com/keep-starknet-strange/unrug-tg-bot/pull/3

feat: Sign Transaction page

---

packages/frontend/src/components/Dropdown/index.tsx
packages/frontend/src/components/Dropdown/style.css.ts
packages/frontend/src/components/Input/index.tsx
packages/frontend/src/components/Layout/App/index.tsx
packages/frontend/src/components/Layout/Home.tsx
packages/frontend/src/components/Modal/Content.tsx
packages/frontend/src/components/Slider/index.tsx
packages/frontend/src/components/Web3Provider/index.tsx
packages/frontend/src/components/common/Portal/index.tsx
packages/frontend/src/hooks/useClickOutside.ts
packages/frontend/src/hooks/useDropdown.ts
packages/frontend/src/pages/Token/Metrics.tsx
packages/frontend/src/pages/Token/style.css.ts

Resolves issue: https://github.com/keep-starknet-strange/unruggable.meme/issues/230
Fix video:
https://github.com/keep-starknet-strange/unruggable.meme/assets/45929094/591ad05f-6b15-4ed8-bb48-7c95df0f70f5
Dev test plan:
- Run app locally.
- Now, go http://localhost:3000/token/0x06e2c03e31f6cda18484ed035c02a25d6075393e11da24c898337f736716acae
- Click on dropdown button (button with 3 dots).
- Make sure that dropdown opens.
- Now, click outside of dropdown and verify that dropdown closes as expected.
- Edge case: Click on dropdown button and verify that dropdown closes as expected rather than re-opening.

Fix: Click outside of dropdown to close the dropdown

---

packages/backend/package.json

This PR fixes the backend build error by removing unused `build` command and `pkgroll` dev dependency

fix: Backend build error

---

.github/workflows/contracts_build.yml
.github/workflows/contracts_test.yml

Fixes the wrong working directory path in github action files. These paths changed when the repo was converted into a monorepo in PR #223

ci: Fix contracts directory path

---

packages/tg-bot/package.json
yarn.lock

This PR fixes the tg-bot build error by removing unused `build` command and `pkgroll` dev dependency

fix: Telegram Bot build error

---

.github/workflows/core.yml
.github/workflows/hooks.yml
packages/core/package.json
packages/core/src/constants/contracts.ts
packages/core/src/types/tokens.ts
packages/frontend/package.json
packages/frontend/src/components/TransactionModal/index.tsx
packages/frontend/src/components/WalletModal/Option.tsx
packages/frontend/src/components/Web3Provider/index.tsx
packages/frontend/src/constants/networks.ts
packages/frontend/src/hooks/useBalances.ts
packages/frontend/src/hooks/useChainId.ts
packages/hooks/package.json
packages/hooks/src/hooks/internal/useInvalidateOnBlock.ts
packages/hooks/src/providers/Provider.tsx
packages/sdk/package.json
packages/tg-bot/package.json
packages/tg-bot/src/forms/launch.ts
packages/tg-bot/src/utils/constants.ts
packages/tg-bot/src/utils/validation.ts
yarn.lock

Resolves a bug introduced with the PR #282 which upgrades the starknetjs version but ignores @starknet-react/core and @starknet-react/chains packages.
I had to make changes to a few files to be able upgrade it, since there are API changes with the newer versions.
I also fixed minor warnings in the tg-bot package.
I also created 2 new CI jobs for core & hooks packages.
- starknet peer dependency upgraded from >=5.0.0 to >=6.8.0
- @starknet-react/core dependency upgraded from 2.2.4 to 3.6.2
- @starknet-react/core peer dependency upgraded from >=2.0.0 to >=3.0.0
- @starknet-react/chains dependency upgraded from 0.1.0 to 3.1.0
- @tanstack/react-query dependency upgraded from 5.0.1 to 5.25.0
- @starknet-io/types-js dependency installed with version ^0.7.10

fix: token check bug
