frontend/src/App.tsx, frontend/src/components/Button/style.css.ts, frontend/src/components/NavBar/index.tsx, frontend/src/components/NavBar/style.css.ts, frontend/src/pages/Launch.tsx, frontend/src/pages/Manage.tsx, frontend/src/theme/css/vars.css.ts
Add header navigation with `/launch` and `/manage` pages
=> add navigation

assets/Unrug_Risk_Matrix.csv
=> added unrug risk matrix

frontend/README.md
A very simple how-to-build for front-end developers.
=> [doc]Update frontend's readme.

.github/workflows/contracts_build.yml, .github/workflows/contracts_test.yml, .github/workflows/scorecards.yml, contracts/.tool-versions
get versions from .tool-versions file in CI Closes #46
=> CI: use tool-versions

frontend/src/pages/Launch/index.tsx, frontend/src/utils/amount.ts
=> fix Launch form amounts validation

contracts/src/errors.cairo, contracts/src/lib.cairo, contracts/src/token_locker.cairo, contracts/src/tokens/memecoin.cairo, contracts/tests/test_token_locker.cairo, contracts/tests/test_unruggable_memecoin.cairo
After 6 days this is my final commit. If any other conflict merges done before that I am not gonna continue this PR.
=> feat: locker contract

contracts/src/tokens/factory.cairo, contracts/tests/test_unruggable_memecoin_factory.cairo
This method allows frontend to ensure a token has been deployed through the factory without having to rely on an indexer.
=> [contracts] add `is_memecoin` method on factory

contracts/src/tests/test_unruggable_memecoin.cairo, contracts/src/tests/utils.cairo, contracts/src/tokens/memecoin.cairo
@enitrat  I removed some weird unnecessary prank usage  in tests. Also removed declaration of unused variable and corrected the unnecessary `+1` in multicall disable test
Closes #113
=> FEAT: renounce ownership upon launch + small test refactor

frontend/src/components/Modal/Content.css.ts, frontend/src/components/Modal/Content.tsx, frontend/src/theme/css/sprinkles.css.ts
=> Add responsive modal

docs/social/x/Unrug Thread by lachips
Here my humble contribution for Unrug, posted this thread to help people to understand better how unrug is going to work :) And also maybe bring new people !
=> Create Unrug Thread by lachips

contracts/src/utils/decimalScale.ts, frontend/src/constants/contracts.ts, frontend/src/constants/misc.ts, frontend/src/hooks/useMemecoin.ts, frontend/src/pages/Token/index.tsx, frontend/src/state/index.ts
Fetch and display liquidity unlock time from chain.
=> [frontend] Display real liquidity lock period

contracts/src/exchanges/ekubo/launcher.cairo
As reported by @0xEniotna [L-04], 
Ekubo now has a specific function for collecting fees.
https://github.com/EkuboProtocol/abis/blob/0b1368f6bbce61b4d7dbf4a32b3fbc4ddf3b77d7/src/interfaces/positions.cairo#L87
=> audit: replace deprecated collect fee functions

docs/social/x/threads.md
Thread for Unruggable Meme
https://x.com/paulemmanuelng/status/1752665241228312628?s=20
=> feat: add thread link

contracts/src/errors.cairo, contracts/src/factory/factory.cairo, contracts/src/tests/unit_tests/test_factory.cairo
Input checks according issue: https://github.com/keep-starknet-strange/unruggable.meme/issues/189
=> Input checks for ekubo launch

contracts/src/exchanges/jediswap_adapter.cairo, contracts/src/utils/math.cairo
=> feat: launching with unlock_time set to 0 burns the token

contracts/src/exchanges.cairo, contracts/src/exchanges/starkdefi.cairo, contracts/src/exchanges/starkdefi/interfaces.cairo, contracts/src/exchanges/starkdefi/starkdefi_adapter.cairo, contracts/src/factory/factory.cairo, contracts/src/factory/interface.cairo, contracts/src/tests/fork_tests/test_ekubo.cairo, contracts/src/tests/fork_tests/test_starkdefi.cairo, contracts/src/tests/unit_tests/test_factory.cairo, contracts/src/token/memecoin.cairo
#182 
@enitrat here's the new PR
=> feat: add StarkDeFi - [reworked]

frontend/src/components/AddTeamAllocationHolderModal/index.tsx, frontend/src/components/AddTeamAllocationHolderModal/style.css.ts, frontend/src/constants/misc.ts, frontend/src/hooks/useLaunchForm.ts, frontend/src/hooks/useModal.ts, frontend/src/pages/Token/LaunchForm/Confirm/Ekubo.tsx, frontend/src/pages/Token/LaunchForm/Confirm/Jediswap.tsx, frontend/src/pages/Token/LaunchForm/Confirm/index.tsx, frontend/src/pages/Token/LaunchForm/TeamAllocation/HolderSlot.tsx, frontend/src/pages/Token/LaunchForm/TeamAllocation/index.tsx, frontend/src/pages/Token/LaunchForm/TeamAllocation/style.css.ts, frontend/src/pages/Token/Metrics.tsx, frontend/src/pages/Token/index.tsx, frontend/src/state/application.ts, frontend/src/state/launch.ts, frontend/src/theme/css/sprinkles.css.ts, frontend/src/utils/amount.ts, frontend/src/utils/zod.ts
Team allocation informations were previously filled during deployment, but after recent contracts update, it has been moved to the launch step. Following this update, this PR introduces the new team allocation form.
=> [frontend] Team allocation form

frontend/package.json, frontend/src/App.tsx, frontend/src/pages/WalletRedirect/index.tsx, frontend/src/pages/WalletRedirect/style.css.ts, frontend/yarn.lock
Telegram doesn't allow direct deeplinks to apps. For telegram to open argent:// deeplinks, we need a web page that will redirect the user to the destination deeplink.
If user rejects or auto redirect doesnt work, this page will display a qr and a button to open the destination url.
This pr introduces a new light dependency, [QRCode](https://www.npmjs.com/package/qrcode).
https://pkg-size.dev/qrcode
Required By
- keep-starknet-strange/unrug-tg-bot#3
=> Wallet Redirect page

package.json
removed corepack to facilitate vercel deployments
=> Removed corepack

packages/frontend/public/index.html, packages/frontend/src/theme/css/global.css.ts
This PR adds support for twitter slinks
=> feat: Twitter Slinks
